name: Django Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 4
        matrix:
            python-version: '3.13'            
    services:
        postgres:
            image: postgres:14
            env:
                POSTGRES_PASSWORD: ${{ secrets.PASS }}
                POSTGRES_DB: ${{ secrets.DATABASE }}
                TZ: 'America/Argentina/Mendoza'
                PGTZ: 'America/Argentina/Mendoza'
            ports:
                - 5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}
            
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/django/requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in `seq 1 10`; do
          if pg_isready -h localhost -p 5432 -U ${{ secrets.USER }} -d ${{ secrets.DATABASE }}; then
            break
          fi
          sleep 2
        done
            
    - name: Run Tests
      run: |
        cd public/pms/
        python manage.py test
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        HOST: localhost
        DATABASE: ${{ secrets.DATABASE }}
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
        TZ: 'America/Argentina/Mendoza'
