name: Django Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        docker-compose --version

    - name: Build and start containers
      run: |
        docker-compose up -d

    - name: Run migrations
      run: |
        docker-compose exec web python ./pms/manage.py migrate

    - name: Run tests
      run: |
        docker-compose exec web python ./pms/manage.py test

    - name: Stop containers
      run: |
        docker-compose down
