name: Linting and Formatting on PR

on:
  pull_request:
    branches:
      - main  # Cambia a la rama principal de tu proyecto

jobs:
  linting-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Obtiene el código del PR

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: 'true'  # Obtiene los archivos modificados desde el último commit

      - name: Run flake8 on changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == *.py ]]; then  # Filtra solo archivos Python
              flake8 "$file"
            fi
          done

      - name: Run black on changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == *.py ]]; then  # Filtra solo archivos Python
              black --check "$file"
            fi
          done

      - name: Run isort on changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == *.py ]]; then  # Filtra solo archivos Python
              isort --check-only "$file"
            fi
          done