name: Linting and Formatting

on:
  push:
    branches:
      - main  # Cambia a la rama principal de tu proyecto
  pull_request:
    branches:
      - main  # Cambia a la rama principal de tu proyecto

jobs:
  linting-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Especifica la versión de Python que usas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run flake8 (Linting)
        run: |
          flake8 public/pms  # Solo revisa la carpeta public/pms

      - name: Run black (Code Formatting)
        run: |
          black --check public/pms  # Solo revisa la carpeta public/pms

      - name: Run isort (Import Sorting)
        run: |
          isort --check-only public/pms  # Solo revisa la carpeta public/pms